#!/usr/bin/env bash
# Install nginx web server

sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World" > /var/www/html/index.nginx-debian.html

sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://giphy.com/gifs/1wqqlaQ7IX3TXibXZE permanent;' /etc/nginx/sites-available/default

sudo service nginx restart