#!/usr/bin/env bash
# Install and configure HAproxy on my lb-01 server.
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend rmatovu987
        bind *:80
        mode http
        default_backend rmatovu987
backend rmatovu987
        balance roundrobin
        server 380-web-01 35.231.223.136:80 check
        server 380-web-02 3.226.72.197:80 check
"
 echo "$server_config" >> /etc/haproxy/haproxy.cfg

 # enable haproxy to be started by init script

 echo "ENABLED=1" >> /etc/default/haproxy

 sudo service haproxy restart