#!/usr/bin/env bash
#check file status
FILE=school
if [ ! -e "$FILE" ]
then
	echo "school file does not exist"
else
	echo "school file exists"
	if [ -s "$FILE" ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	if [ -f "$FILE" ]
	then
		echo "school is a regular file"
	fi
fi
